### PR TITLE
Update browsers and devices page

### PR DESCRIPTION
**Pull request by tombye**
Changes are mainly updates to the body copy to bring it up to date but also include the removal of Safari 5 & 6 on IOS as their usage has dropped to be a good way out of the top 95%.

I'd be very interested in the opinions of @robinwhittleton, @bradwright, @dsingleton @fofr, @gemmaleigh & @quis on the changes.

Thanks to @bdewater for highlighting the copy problems in issue [600](https://github.com/alphagov/government-service-design-manual/issues/600).

### A quick note on IE7

IE7's usage hasn't changed significantly since @edds mentioned it in [the last update](https://github.com/alphagov/government-service-design-manual/commit/f4fa5f8decbdea48a5a8bfdd0c40ef0f308baf0c) so there's no good reason for dropping it from functional for now. This will be monitored over the next few months to make sure the reasoning still makes sense.

### CODE REVIEW

**Comment by jabley** [comment]
:shipit:

**Comment by quis** [comment]
For reference:

Device | Latest version of Safari supported | Discontinued | Recommended in this PR
---|---|---|---
iPhone 3G | 4 | June 7, 2010 | ✗
iPhone 3GS | 6 | September 12, 2012 | ✗
iPhone 4 | 7 | September 10, 2013 | ✔

**Comment by robinwhittleton** [comment]
This all looks good. My only comment would be that while mobile phones are regularly upgraded, tablets are not. The iPad 2 enjoys support for even iOS9, but the iPad 1 topped out at iOS 5. It might be worth keeping iOS 5 in functional specifically for them (I’ve got no problem in dropping iOS 6 completely). What do the numbers for iPad 1 look like?

**Comment by bdewater** [comment]
Thanks Tom, looking good! Shouldn't IE8 be downgraded to 'functional' along with 7 because it has dropped below 95%? There's also the issue that Microsoft will [stop supporting anything older than IE9](http://blogs.msdn.com/b/ie/archive/2014/08/07/stay-up-to-date-with-internet-explorer.aspx) after January 12, 2016. Downgrading IE8 would be a nudge in the right direction for people to upgrade their browser :)

**Comment by bradwright** [comment]
IE8 is currently 2.4% on GOV.UK.

**Comment by tombye** [comment]
@robinwhittleton iOS for tablet is currently at 0.3% of all visits and has dropped by about 0.1% since June. It's also been outside of the 95% since the last updates.

Bearing in mind it's at the same level as Amazon's Silk browser (for Kindle fire) which isn't in the support matrix I'd say iOS 5 should stay out too, at least until the next round of updates.

**Comment by robinwhittleton** [comment]
OK, that’s good enough for me!

**Pull request merged**
