### PR TITLE
Remove guidance to separate username and password

### PR DESCRIPTION
**Pull request by joelanman**
In research on GOV.UK Verify, we've found this specific situation - username & password, to work better on a single page.

When separated, people would get confused by the similarity of the two pages, and sometimes assume that the second page was simple a validation of the first.

### CODE REVIEW

**Comment by joelanman** [comment]
@cjforms any thoughts?

**Comment by jabley** [comment]
@joelanman the bit you've deleted references previous research for GOV.UK Verify. So you now have conflicting results from new research?

**Comment by cjforms** [comment]
The research from Verify is an interesting story that's not been written up yet. Let's get the writing up part done first, and then do a pull request that tidies up the service manual based on it.

**Comment by joelanman** [comment]
@jabley yes - initially it seemed promising. "One thing per page" seems to be a powerful way to approach things in general. However, over time, in this particular context, we saw the issues I've mentioned above:

> When separated, people would get confused by the similarity of the two pages, and sometimes assume that the second page was simple a validation of the first.

@cjforms when you say written up - do you mean a blog post?

**Comment by joelanman** [comment]
@timpaul Caroline suggested getting your opinion on this. Could we remove this suggestion, as we now have research to say it can be confusing.

**Comment by daibach** [comment]
Is there any update to this? I'm going to close this pull request for now until we've come to a decision.

**Pull request closed without merging**
