### PR TITLE
Update references to SSL to use TLS

### PR DESCRIPTION
**Pull request by jabley**
Since POODLE, we should not encourage any usage of SSL. Instead, we
should explicitly encourage TLS.

Googling for TLS vendors returns what I would expect; namely, SSL
vendors.

### CODE REVIEW

**Comment by alexmuller** [comment]
I agree with this except that Google returns 38,000 results for "tls certificates" but 16,000,000 results for "ssl certificates".

**Comment by jabley** [comment]
We only want to work with vendors that understand SEO :grin:

That was my main concern with this. People will be used to talking about SSL, when really they mean TLS.

SSL / TLS is a [server](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_protocols) [configuration](http://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslprotocol) [issue](https://www.digicert.com/ssl-support/iis-disabling-ssl-v3.htm), rather than a vendor issue though.

(Yes, I've linked to Digicert for IIS config, rather than MSDN, since the MSDN articles all seem to say 'Hack about in the Registry').

**Comment by ajlanghorn** [comment]
I think an addition to say that you should _only_ be using TLSv1.2 and later is a good addition. Happy to make this change myself if you like, @jabley; just let me know :)

Other than that, a good PR. A+++. Would consider merging again :+1:

**Comment by jabley** [comment]
Having second thoughts about this. I think it's [similar to 'holiday entitlement' versus 'holiday pay'](https://gds.blog.gov.uk/2012/07/10/the-seo-war-fighting-the-good-fight-in-search/), and we should use the vocabulary our audience use. This is likely to be SSL still.

Also not sure about @ajlanghorn suggestion about TLSv1.2. I think that would exclude a large portion of our traffic. We should probably [track what CDNs use](https://github.com/cloudflare/sslconfig/blob/d6529d3c4da26859a78bb1e64e1d151ad5f78c9e/conf).

**Comment by ajlanghorn** [comment]
Okay, TLSv1 is better than SSLv3 in hindsight.

**Comment by daibach** [comment]
This pull request hasn't been updated for a while. I'm closing it for now.

**Comment by ajlanghorn** [comment]
Returning to my TLS comment, I think that since TLS1 is fast becoming obsolete (despite the fact that CDNs still support it), standardising on TLS 1.1 and 1.2 for new services would be good. Existing stuff can probably still keep running TLS1, but there should maybe be a section advising that things are upgraded sooner rather than later.

**Comment by ajlanghorn** [comment]
Anyway, A+ PR hygiene, @daibach :)

**Pull request closed without merging**
