### PR TITLE
Update progress indicator pattern

### PR DESCRIPTION
**Pull request by timpaul**
We've updated the guidance given here so that it better reflects what we've been telling service teams recently.

### CODE REVIEW

**Comment by cjforms** [comment]
This pull request is a much-needed update of our advice on progress indicators that takes account of research over the last 18 months. Please merge.

**Comment by issyl0** [comment]
Hi @timpaul. These changes look good, though would you mind squashing these three commits together so as to have clean history, perhaps with the commit message "Update progress indicator pattern guidance"? These three commits are slight changes and syntax fixes each time. If you need a hand, http://stackoverflow.com/a/6934882 hopefully makes sense, but if it doesn't, I'm around to help, or I could do it for you (though maybe you wouldn't take too kindly to that - I don't know).

**Comment by issyl0** [comment]
I've just rebased this branch and squashed the three commits into one in preparation for merging. :+1:

**Comment by joelanman** [comment]
thanks @issyl0 !

**Comment by timpaul** [comment]
Thanks @issyl0 - sorry I didn't get around to it myself!

**Pull request merged**
