### PR TITLE
Properly capitalise DevOps

### PR DESCRIPTION
**Pull request by ajlanghorn**
DevOps is a portmanteau of 'development' and 'operations', and in some ways
is a good reflection of one of its core tenets. Since each word can be used
individually, we should style this correctly.

Colloboration amongs operations and development teams is central to DevOps,
so since neither party rules the roost all the time, we should capitalise
the start of each part of the portmanteau.

### CODE REVIEW

**Comment by alexmuller** [comment]
Older discussion at https://github.com/alphagov/government-service-design-manual/pull/82#issuecomment-16284855.

**Comment by issyl0** [comment]
Bah. Shall I revert this merge?

**Comment by alexmuller** [comment]
I don't think it's that important :)

**Comment by ajlanghorn** [comment]
@issyl0 No, I don't think so. If another PR wishes to revert it, they can do so and it can be considered at that point.

**Comment by issyl0** [comment]
:+1:

**Pull request merged**
