### PR TITLE
Don't automatically tab between fields

### PR DESCRIPTION
**Pull request by joelanman**
this is general advice, but occurs most often in this pattern

### CODE REVIEW

**Comment by Demotive** [comment]
+1 - totally agree

**Comment by jabley** [comment]
I agree with this personally. Do we have evidence which we could link to?

**Comment by Demotive** [comment]
Hmm good point. Mine's a personal agreement too.
However the fact that something like automatic tabbing actively interferes with default controls (ever tried to shift-tab back through something like this?) means perhaps one shouldn't have to "prove" this?

**Comment by timpaul** [comment]
I've seen people stumble in user research enough time to be convinced it's sound advice. A few other arguments against: 

- It's even harder for screen reader users to spot that they've been tabbed
- If you allow for multiple formats within a field (eg. '1', '01' or 'Jan'), how do you know when to tab?

**Comment by cjforms** [comment]
+1 to agree with it, and support Tim's evidence. 

(At some point, let's do a line-by-line assessment of where we want to document what we've seen in user research as blog posts / other publications to refer to. But let's not postpone publishing good practice just because we haven't got time to write up a formal evidence thing yet).

**Pull request merged**
