### PR TITLE
Update user satisfaction guidance following comments from content editor

### PR DESCRIPTION
**Pull request by henryhadlow**
James Pallister in the content team took a look and suggested some changes.

And I somehow got the Feedback page guidance in here in a bodge merge.

### CODE REVIEW

**Comment by alexmuller** [comment]
I force-pushed to this branch to remove the now-unused image, hope that's ok. This looks good to me :+1:

**Comment by henryhadlow** [comment]
@alexmuller Hey, the image is still used :/ in `feedback-pages.md`

**Comment by alexmuller** [comment]
The image `/service-manual/assets/images/feedback-page.png`? I'm pretty sure it's not, but it's not that important.

**Comment by henryhadlow** [comment]
Doh! I'll put a PR in to add it back in.

On 10 September 2015 at 14:51, Alex Muller <notifications@github.com> wrote:

> The image /service-manual/assets/images/feedback-page.png? I'm pretty
> sure it's not, but it's not that important.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alphagov/government-service-design-manual/pull/597#issuecomment-139240536>
> .
>



-- 
Henry Hadlow
Designer
Government Digital Service <https://gds.blog.gov.uk/>

**Pull request merged**
